export const sliderItems = [
    {
        id: 1,
        // Comment the image below of laptop during development its a heavy image 
        
        img: "https://www.pngall.com/wp-content/uploads/9/Gadget-PNG-Pic.png",
        title: "GGE Tech Store",
        desc: "Wide range of choices from mobile phones, tablets, computer hardware and consoles! Satisfaction guaranteed! Safe delivery to your doorstep! ",
        bg: "e9f6ff",
        link: "/React-Project-e-commerce-app-estore.com/productview/0",
        size: "70%"
    },
    {
        id: 2,
        img: "http://cdn.shopify.com/s/files/1/0593/9727/5805/products/iphone-13-pro-max-graphite-select_cb9edf31-3fd4-4f27-8ed6-978343b9313d_1200x1200.png?v=1643889724",
        title: "IPHONE 13 Pro",
        desc: "Apple iPhone 13 Pro smartphone. Announced Sep 2021. Apple A15 Bionic chipset, 3095 mAh battery, 1024 GB storage, 6 GB RAM, ..",
        bg: "f9f6ff",
        link: "/React-Project-e-commerce-app-estore.com/productview/10",
        size: "80%"
    },
    {
        id: 3,
        img: "https://fonepro.pk/wp-content/uploads/2022/05/1WH-1000XM5_standard_black.png",
        title: "WH-1000XM5",
        desc: "SONY HD Wireless Noise Cancelling Headphones WH-1000XM5 Register before 2022/8/14 to enjoy 500 coffee coupons.",
        bg: "e9e9e9cc",
        link: "/React-Project-e-commerce-app-estore.com/productview/20",
        size: "80%"
    },
    {
        id: 4,
        img: "https://www.pngall.com/wp-content/uploads/9/Electronics-Gadget-PNG.png",
        title: "Amplify your Tech Swag with us!",
        desc: "A wide range of choices! Satisfaction guaranteed! Delivery to your doorstep!",
        bg: "b7bfe4",
        link: "/React-Project-e-commerce-app-estore.com/productlist/headphones",
        size: "80%"
    },

    {
        id: 5,
        img: "https://pngroyale.com/wp-content/uploads/2022/03/Graphic-Web-Design-Transparent-Image.png",
        title: "From Windows to Mac",
        desc: "Diverse product range",
        bg: "e9f6ff",
        link: "/React-Project-e-commerce-app-estore.com/productlist/laptops",
        size: "80%"
    },

];

export const categories = [
    {
        id: 1,
        img: "https://www.cnet.com/a/img/resize/749c306c97f14076499981fc018dace33d0e367d/hub/2018/02/13/517fda12-de2a-4c3f-bee5-05daaf870537/01laptops-with-longest-battery-life-2018-feb.jpg?auto=webp&width=1200",
        title: "LAPTOPS",
        link: "/React-Project-e-commerce-app-estore.com/productlist/laptops",
    },
    {
        id: 2,
        img: "https://www.cnet.com/a/img/resize/55fb60ca6a8cf5035ac2b5044ef54e6f87f6be3f/2020/08/18/b7168aea-9f7e-47bb-9f31-4cb8ad92fbc7/lg-note-20-ultra-5g-iphone-11-se-google-pixel-4a-lg-velvet-6133.jpg?auto=webp&fit=crop&height=675&width=1200",
        title: "PHONES",
        link: "/React-Project-e-commerce-app-estore.com/productlist/phones",
    },
    {
        id: 3,
        img: "https://i.pcmag.com/imagery/articles/06X5FmHnKHTTmFzyn5jMunR-7..v1651759223.jpg",
        title: "HEADPHONES",
        link: "/React-Project-e-commerce-app-estore.com/productlist/headphones",
    },
    {
        id: 4,
        img: "https://wallpapers.com/images/high/playstation-ps5-console-nsndc8ewygduy1nh.jpg",
        title: "CONSOLES",
        link: "/React-Project-e-commerce-app-estore.com/productlist/consoles",
    },
];

export const allProducts = [
    // Products all here 
    // Product Id starts from zero same as index to object
    {
        id: 0,
        title: "MACBOOK PRO 13-inch",
        desc: "M2 is the next generation of Apple silicon. Its 8-core CPU lets you zip through everyday tasks like creating documents and presentations, or take on more intensive workflows like developing in Xcode or mixing tracks in Logic Pro.",
        img: "https://www.applestore.pk/wp-content/uploads/2021/01/mbp-spacegray-select-202011.jpg",
        // Price and Price Quantity must be same
        price: 86990,
        priceQuantity: 86990,
        quantity: 1,
        category: "laptops",
        popular: "yes",
        "Main Features": "8-Core CPU | 10-Core GPU",
        specs: {
            RAM: "6 GB",
            ROM: "256 GB",
            "Display": "Retina display",
            "Battery and Power": "4Up to 20 hours Apple TV app movie playbackGB",
            "Memory": "8GB unified memory",
            "Storage": "256GB SSD",
            "Charg­ing and Expan­sion": "Two Thunderbolt / USB 4 ports",
            "Key­board and Track­pad": "Backlit Magic Keyboard",
            "Wireless": "Wi-Fi 802.11ax Wi-Fi 6 wireless networking",
            "Bluetooth": "Bluetooth 5.0 wireless technology",
            "Camera": "720p FaceTime HD camera",
            "Audio": "Stereo speakers with high dynamic range",
            "Display Support": "Native DisplayPort output over USB‑C",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 1,
        title: "HP 15s FQ5886TU",
        desc: "The HP 15 Laptop is thoughtfully designed and delivers performance with an Intel i5 processor, fast Wi-Fi technology, and loads of storage. Enjoy a more natural and comfortable typing position with the lift-hinge design and enlarged click pad. The HP 15 design includes sustainable materials like ocean-bound plastic and from post-consumer recycled plastic",
        img: "https://laptopmart.pk/wp-content/uploads/2022/08/HP-Laptop-15s-fq2555TU.jpg",
        // Price and Price Quantity must be same
        price: 35635,
        priceQuantity: 35635,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "Intel Core i5",
        specs: {
            RAM: "16 GB",
            ROM: "512 GB SSD",
            "Display": " 15 inch FHD (1920 x 1080), IPS, micro-edge, anti-glare ",
            "Battery and Power": "3-cell, 41 Wh Li-ion",
            "Memory": " DDR4-3200 MHz RAM (2 x 8 GB) ",
            "Storage": " 512 GB PCIe® NVMe™ M.2 SSD ",
            "Charg­ing and Expan­sion": " 1 SuperSpeed USB Type-C® 5Gbps signaling rate; 2 SuperSpeed USB Type-A 5Gbps signaling rate; ***  1 HDMI 1.4b; 1 AC smart pin; 1 headphone/microphone combo ",
            "Key­board and Track­pad": " Full sized keyboard with numpad and trackpad ",
            "Wireless": " 802.11a/b/g/n/ac (2x2) Wi-Fi® ",
            "Bluetooth": " Bluetooth® 5 ",
            "Camera": " HP True Vision 720p HD camera with integrated dual array digital microphones ",
            "Audio": " Dual speakers ",
            "Display Support": " - ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 2,
        title: "HP ENVY x360",
        desc: "The HP ENVY x360 15.6 inch 2-in-1 is a carefully crafted touchscreen laptop with a powerful Intel i7 processor. Featuring a HD display[2] and narrow bezels, you can see your more of your digital world. Enjoy peace of mind with added security features like an integrated fingerprint reader[3], physical camera shutter and microphone mute button.",
        img: "https://laptopmart.pk/wp-content/uploads/2022/08/HP-ENVY-x360-15-ew0023dx-new.jpg",
        // Price and Price Quantity must be same
        price: 64790,
        priceQuantity: 64790,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "Intel Core i7",
        specs: {
            RAM: "16 GB",
            ROM: "512 GB",
            "Display": " LCD: 40.9 cm (16.1 inch) diagonal, FHD (1920 x 1080), IPS, micro-edge, anti-glare, 300 nits, 100% sRGB ",
            "Battery and Power": " 4-cell, 70 Wh Li-ion polymer ",
            "Memory": " 16 GB DDR4-3200 MHz RAM (2 x 8 GB) ",
            "Storage": " 512 GB PCIe® NVMe™ TLC M.2 SSD ",
            "Charg­ing and Expan­sion": " SuperSpeed USB Type-C ",
            "Key­board and Track­pad": " Full sized keyboard with numpad and trackpad ",
            "Wireless": " WLAN: Realtek Wi-Fi 6 (2x2) ",
            "Bluetooth": " Bluetooth® 5.2 combo ",
            "Camera": " HP Wide Vision 720p HD camera with camera shutter, temporal noise reduction and integrated dual array digital microphones ",
            "Audio": " Audio by Bang & Olufsen; Dual speakers; HP Audio Boost ",
            "Display Support": " - ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 3,
        title: "HP Victus",
        desc: "Powered by an AMD Ryzen 7 Processor 5800H (up to 4.4 GHz max boost clock, 16 MB L3 cache, 8 cores, 16 threads) with NVIDIA® GeForce RTX™ 3050 Ti Laptop GPU (4 GB GDDR6 dedicated), the Victus by HP 16.1 inch Gaming Laptop PC has the features to handle your game. The all-purpose gaming keyboard, fast refresh rate and high-res display give you an immersive experience. Power through the heat with an upgraded cooling system.",
        img: "https://laptopmart.pk/wp-content/uploads/2022/07/HP-Victus-Gaming-15-fa0031dx.jpg",
        // Price and Price Quantity must be same
        price: 60759,
        priceQuantity: 60759,
        quantity: 1,
        category: "laptops",
        popular: "yes",
        "Main Features": " Ryzen 7 ",
        specs: {
            RAM: "32 GB",
            ROM: "1 TB",
            "Display": " 16.1 inch diagonal, FHD (1920 x 1080), 144 Hz, 7 ms response time, IPS, micro-edge, anti-glare, Low Blue Light, 300 nits, 100% sRGB ",
            "Battery and Power": " 4-cell, 70 Wh Li-ion polymer ",
            "Memory": " 32 GB DDR4-3200 MHz RAM (2 x 16 GB) ",
            "Storage": " 1 TB PCIe® NVMe™ TLC M.2 SSD ",
            "Charg­ing and Expan­sion": "200 W Smart AC power adapter",
            "Key­board and Track­pad": " gaming keyboard with trackpad ",
            "Wireless": " Realtek Wi-Fi 6 (2x2) ",
            "Bluetooth": " Bluetooth® 5.2 combo ",
            "Camera": " HP Wide Vision 720p HD camera with integrated dual array digital microphones ",
            "Audio": " Audio by Bang & Olufsen; Dual speakers; HP Audio Boost ",
            "Display Support": " - ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 4,
        title: "Dell Inspiron 15",
        desc: "Dell Inspiron 15 is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM.",
        img: "https://laptopmart.pk/wp-content/uploads/2022/05/Dell-Inspiron-15-3515.jpg",
        // Price and Price Quantity must be same
        price: 54990,
        priceQuantity: 54990,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "Quad Core",
        specs: {
            RAM: "8 GB",
            ROM: "512 GB",
            "Display": " 15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display ",
            "Battery and Power": " 3-Cell Battery, 41WHr (Integrated) ",
            "Memory": " 8GB, 1x8GB, DDR4, 3200MHz ",
            "Storage": " 1 TB M.2 PCIe NVMe Solid State Drive ",
            "Charg­ing and Expan­sion": " 65 Watt AC Adapter ",
            "Key­board and Track­pad": " Non-Backlit Keyboard and trackpad ",
            "Wireless": " 802.11ac 1x1 WiFi ",
            "Bluetooth": " Bluetooth 4 ",
            "Camera": " 720p at 30 fps HD camera, single-integrated microphone ",
            "Audio": " Stereo speakers, 2 W x 2 = 4 W total ",
            "Display Support": " - ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 5,
        title: "Dell G7 15 7500",
        desc: "17-inch gaming laptop with thin, sleek design, 10th Gen Intel® Core™ i7-10750H (12 MB Cache, 6 Core, 2.6 GHz to 5 GHz) processors with NVIDIA® GeForce® RTX™ 2070 Super, 8 GB GDDR6, Game Shift technology and 4-zone RGB keyboard.",
        img: "https://laptopmart.pk/wp-content/uploads/2021/05/Dell-G7-15-7500-RGB-New.jpg",
        // Price and Price Quantity must be same
        price: 94555,
        priceQuantity: 94555,
        quantity: 1,
        category: "laptops",
        popular: "yes",
        "Main Features": "Hexa-Core",
        specs: {
            RAM: "32 GB",
            ROM: "2 TB",
            "Display": " 17.3-inch, FHD 1920 x 1080, 144 Hz, anti-glare, non-touch, 72% NTSC, 300 nits, wide-viewing angle ",
            "Battery and Power": " 6-cell 97 WHr smart lithium-ion, ExpressCharge™, integrated ",
            "Memory": " 32 GB, 2 x 16 GB, DDR4, 2933 MHz, dual-channel ",
            "Storage": " 2 TB, M.2 2280, PCIe NVMe Gen3 x4, SSD ",
            "Charg­ing and Expan­sion": " 240W 12.3A AC Power laptop Adapter Charger ",
            "Key­board and Track­pad": " 4-zone RGB, English US, backlit keyboard ",
            "Wireless": " Intel® AX201, 2x2, MIMO, 2.4/5 GHz, Wi-Fi 6 (WiFi 802.11ax) ",
            "Bluetooth": "  Bluetooth 5.0 ",
            "Camera": " 720p at 30 fps, HD RGB camera, Dual microphones in camera assembly ",
            "Audio": " Realtek ALC3281 audio controller 2 W x 2 = 4 W total with dual-array microphones ",
            "Display Support": " Supports USB 3.1 Gen 2, DisplayPort 1.2, Thunderbolt 3 ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 6,
        title: "MSI GL75 Leopard",
        desc: "MSI GL75 Leopard is the go-to option for GeForce RTX 2070 and 10th Gen intel core i7 portable gaming laptop.",
        img: "https://laptopmart.pk/wp-content/uploads/2020/09/MSI-GL75-Leopard-10SDR-144Hz.jpg",
        // Price and Price Quantity must be same
        price: 84999,
        priceQuantity: 84999,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "Core i7-10th",
        specs: {
            RAM: "16 GB",
            ROM: "1 TB",
            "Display": " 17.3 inch FHD (1920x1080), 144Hz 3ms, IPS-Level 72%NTSC Thin Bezel, close to 100%sRGB ",
            "Battery and Power": " 6 cell (51Whr) ",
            "Memory": " 16GB (8G*2) DDR4 2666MHz ",
            "Storage": " 1 TB NVMe SSD ",
            "Charg­ing and Expan­sion": " 230W AC Power Adaptor ",
            "Key­board and Track­pad": " Steel Series per-Key RGB with Anti-Ghost key+ silver lining ",
            "Wireless": " Intel Wi-Fi 6 AX201(2*2 ax) ",
            "Bluetooth": " BT 5.1 ",
            "Camera": " 720p HD Webcam ",
            "Audio": " Giant Speakers 3W*2 ",
            "Display Support": " HDMI (supports 4K @ 60Hz), mDP v1.2*1 ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 7,
        title: "ThinkPad X1 Carbon",
        desc: "Marries premium performance & mobility. With Intel i7-8650U and UHD Graphics 620",
        img: "https://laptopmart.pk/wp-content/uploads/2020/01/ThinkPad-X1-Carbon-7th-Gen.jpg",
        // Price and Price Quantity must be same
        price: 49199,
        priceQuantity: 49199,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "Core i7",
        specs: {
            RAM: "16 GB",
            ROM: "2 TB",
            "Display": "  In-plane Switching (IPS) Technology, Screen Resolution: 1920 x 1080, Touchscreen ",
            "Battery and Power": " 3-cell Lithium Polymer Battery ",
            "Memory": " 16 GB LPDDR3 ",
            "Storage": " 2 TB Solid State Drive ",
            "Charg­ing and Expan­sion": " 230 V AC Adapter ",
            "Key­board and Track­pad": " Backlit Keyboard and Trackpad ",
            "Wireless": " 802.11g ",
            "Bluetooth": " Bluetooth 4 ",
            "Camera": " ThinkShutter with HD webcam ",
            "Audio": " Dolby Atmos® Speaker System ",
            "Display Support": " USB Type C ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 8,
        title: "Lenovo ThinkBook",
        desc: "Produce your best work yet with the Lenovo ThinkBook 14 Gen 4 laptop. This device is packed with powerful features like 10th Gen Intel® Core™ i Series processor, plus optional dual SSD storage and up to WiFi 6E connectivity. Its 14 inch display boasts up to FHD resolution with vivid brightness, optional touchscreen, and 100% sRGB color gamut, so you can see every detail of your work and navigate through your screen with ease.",
        img: "https://laptopmart.pk/wp-content/uploads/2021/10/Lenovo-ThinkBook-15-IIL-ci3-new.jpg",
        // Price and Price Quantity must be same
        price: 84999,
        priceQuantity: 84999,
        quantity: 1,
        category: "laptops",
        popular: "no",
        "Main Features": "10th Generation",
        specs: {
            RAM: "4 GB",
            ROM: "1 TB",
            "Display": " 15.6 inch FHD (1920 x 1080), TN, Anti-Glare, Non-touch, 45%NTSC, 250 nits, 60Hz, Narrow Bezel ",
            "Battery and Power": " - ",
            "Memory": " 4 GB DDR4-3200MHz ",
            "Storage": " 1 TB SSD M.2 2242 PCIe Gen3 TLC ",
            "Charg­ing and Expan­sion": " 65W USB-C AC Adapter Black (3pin) ",
            "Key­board and Track­pad": " Iron Grey Keyboard with Fingerprint reader ",
            "Wireless": " Wi-Fi 6 2x2 AX ",
            "Bluetooth": " Bluetooth® 5.0 ",
            "Camera": " HD with Dual Array Microphone ",
            "Audio": " Stereo speakers with Dolby Audio™ ",
            "Display Support": " USB-C Thunderbolt™ 4, HDMI 2.1 TDMI ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 9,
        title: "Acer Nitro 5",
        desc: "Reign over the game world with the combined power of a 12th Gen Intel® Core™ i7 processor1 with its new performance hybrid architecture and NVIDIA GeForce RTX 30 series",
        img: "https://laptopmart.pk/wp-content/uploads/2022/06/Acer-Nitro-5-AN515-57-536Q.jpg",
        // Price and Price Quantity must be same
        price: 58999,
        priceQuantity: 58999,
        quantity: 1,
        category: "laptops",
        popular: "yes",
        "Main Features": "11th Generation",
        specs: {
            RAM: "8 GB",
            ROM: "256",
            "Display": " 15.6″ display with IPS and Full HD 1920 x 1080 resolution, supporting 144 Hz and GSYNC ",
            "Battery and Power": " 57.5 Wh Lithium Ion (Li-Ion) ",
            "Memory": " 8 GB LPDDR4 SDRAM ",
            "Storage": " 256 GB Expandable up to 1TB SSD (1x M.2 slot) ",
            "Charg­ing and Expan­sion": " 3-pin 180 W AC adapter ",
            "Key­board and Track­pad": " 4 zone RGB keyboard ",
            "Wireless": " IEEE 802.11a/b/g/n/acR2+ax ",
            "Bluetooth": " Bluetooth 5.1 ",
            "Camera": " 1280 x 720 resolution with HD audio/video recording ",
            "Audio": " dual 2W speakers ",
            "Display Support": " USB 3.2(Type-C) Port ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 10,
        title: "iPhone 13 Pro",
        desc: "Apple iPhone 13 Pro smartphone. Announced Sep 2021. Features 6.1″ display, Apple A15 Bionic chipset, 3095 mAh battery, 1024 GB storage, 6 GB RAM.",
        img: "http://cdn.shopify.com/s/files/1/0326/0291/4952/products/iphone13promax_silver_img2_1024x.jpg?v=1639460503",
        // Price and Price Quantity must be same
        price: 64999,
        priceQuantity: 64999,
        quantity: 1,
        category: "phones",
        popular: "yes",
        "Main Features": "A15 Bionic",
        specs: {
            RAM: "6 GB",
            ROM: "256 GB",
            "Network Technology": "GSM / CDMA / HSPA / EVDO / LTE / 5G",
            "Announced": "2021, September 14",
            "Status": "Available. Released 2021, September 24",
            "Dimensions": "146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)",
            "Weight": "204 g (7.20 oz)",
            "Card slot": "No",
            "Internal": "128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM, 1TB 6GB RAM",
            "MAIN CAMERA": "12 MP, f/1.5, 26mm (wide), 1.9µm, dual pixel PDAF, sensor-shift OIS",
            "SELFIE CAMERA": "12 MP, f/2.2, 23mm (wide), 1/3.6",
            "Loudspeaker": "Yes, with stereo speakers",
            "WLAN": "Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot",
            "Sensors": "Face ID, accelerometer, gyro, proximity, compass, barometer",
            "BATTERY": "Li-Ion 3095 mAh, non-removable (12.11 Wh)",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 11,
        title: " Redmi 10A",
        desc: "Android 11, MIUI 12.5 MediaTek Helio G25CPU: Octa-core CPU, up to 2.0GHzGPU: PowerVR8320, up to 650MHz",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_790PYKaHZeujfj3BxH89syS7cdmxrzrdO0Ztz3AE.jpg",
        // Price and Price Quantity must be same
        price: 7999,
        priceQuantity: 7999,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "Dual Sim",
        specs: {
            RAM: "4 GB",
            ROM: "64 GB",
            "Network Technology": " GSM / HSPA / CDMA2000 / LTE ",
            "Announced": " 2022, March 29 ",
            "Status": " Available. Released 2022, March 31 ",
            "Dimensions": " 164.9 x 77.1 x 9 mm ",
            "Weight": " 194 g ",
            "Card slot": " Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 64GB ",
            "MAIN CAMERA": " 13 MP, f/2.2, (wide), 1.0µm, AF ",
            "SELFIE CAMERA": " 5 MP ",
            "Loudspeaker": " Yes ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (rear-mounted), accelerometer, proximity ",
            "BATTERY": " Li-Ion 5000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 12,
        title: "Galaxy A53",
        desc: "Android 12, One UI 4.1 Exynos 1280 (5 nm) CPU Octa-core (2x2.4 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55) GPU Mali-G68",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_mtf5HL4AFSsfV8c6w1fMUXcmMvX6CI7QVZJKLEsa.jpg",
        // Price and Price Quantity must be same
        price: 17999,
        priceQuantity: 17999,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "feature",
        specs: {
            RAM: "6 GB",
            ROM: "128 GB",
            "Network Technology": " GSM / HSPA / LTE / 5G ",
            "Announced": " 2022, March 17 ",
            "Status": " Available. Released 2022, March 24 ",
            "Dimensions": " 159.6 x 74.8 x 8.1 mm ",
            "Weight": " 189 g ",
            "Card slot": " Hybrid Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 128GB expandable microSDXC (uses shared SIM slot)",
            "MAIN CAMERA": " 64 MP, f/1.8, 26mm (wide), 1/1.7X inch, 0.8µm, PDAF, OIS ",
            "SELFIE CAMERA": " 32 MP, f/2.2, 26mm (wide) ",
            "Loudspeaker": " Yes, with stereo speakers ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (under display, optical), accelerometer, gyro, compass, barometer, Virtual proximity sensing ",
            "BATTERY": " Li-Po 5000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 13,
        title: "Redmi Note 11",
        desc: "Android 11, upgradable to Android 12, MIUI 13 Qualcomm SM6225 Snapdragon 680 4G (6 nm) CPU Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver) GPU Adreno 610",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_30a6KkjTniM8zVJhn2dyWEupB09fgh8iRn4278Fj.jpg",
        // Price and Price Quantity must be same
        price: 11999,
        priceQuantity: 11999,
        quantity: 1,
        category: "phones",
        popular: "yes",
        "Main Features": "Dual Sim",
        specs: {
            RAM: "4 GB",
            ROM: "128 GB",
            "Network Technology": " GSM / HSPA / LTE ",
            "Announced": " 2022, January 26 ",
            "Status": " Available. Released 2022, February 09 ",
            "Dimensions": " 159.9 x 73.9 x 8.1 mm ",
            "Weight": " 179 g ",
            "Card slot": " Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 128 GB ",
            "MAIN CAMERA": " 50 MP, f/1.8, 26mm (wide), 1/2.76, 0.64µm, PDAF ",
            "SELFIE CAMERA": " 13 MP, f/2.4, (wide), 1/3.1, 1.12µm ",
            "Loudspeaker": " Yes, with stereo speakers ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (side-mounted), accelerometer, gyro, compass ",
            "BATTERY": " Li-Po 5000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 14,
        title: "Xiaomi 12",
        desc: "Android 12, MIUI 13 Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm) CPU Octa-core (1x3.00 GHz Cortex-X2 & 3x2.50 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510) GPU Adreno 730",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_ElV9FgUiq9jCyjpugsvtEDMuCQDHAKDe3Uj28Axg.jpg",
        // Price and Price Quantity must be same
        price: 31999,
        priceQuantity: 31999,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "Dual Sim",
        specs: {
            RAM: "6 GB",
            ROM: "256 GB",
            "Network Technology": " GSM / CDMA / HSPA / EVDO / LTE / 5G ",
            "Announced": " 2021, December 28 ",
            "Status": " Available. Released 2021, December 31 ",
            "Dimensions": " 152.7 x 69.9 x 8.2 mm ",
            "Weight": " 179 g  ",
            "Card slot": " Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 256 GB ",
            "MAIN CAMERA": " 50 MP, f/1.9, 26mm (wide), 1/1.56, 1.0µm, PDAF, OIS ",
            "SELFIE CAMERA": " 32 MP, f/2.5, 26mm (wide), 0.7µm ",
            "Loudspeaker": " Yes, with stereo speakers ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac/6 or 6e (market dependent), dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (under display, optical), accelerometer, gyro, compass, color spectrum, Virtual Proximity Sensing ",
            "BATTERY": " Li-Po 4500 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 15,
        title: "Vivo V23e",
        desc: "Android 11, Funtouch 12 Mediatek Helio G96 (12 nm) CPU Octa-core (2x2.05 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55) GPU Mali-G57 MC2",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_DZTVy7B93gsEVtUuf3GuzKnR94jq2tPfyLTGu7kg.jpg",
        // Price and Price Quantity must be same
        price: 18999,
        priceQuantity: 18999,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "feaDual Simture",
        specs: {
            RAM: "8 GB",
            ROM: "256 GB",
            "Network Technology": " GSM / CDMA / HSPA / LTE ",
            "Announced": " 2021, November 09 ",
            "Status": " Available. Released 2021, November 09 ",
            "Dimensions": " 160.9 x 74.3 x 7.4 mm ",
            "Weight": " 172 g ",
            "Card slot": " Hybrid Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 256 GB ",
            "MAIN CAMERA": " 64 MP, f/1.8, 26mm (wide), PDAF ",
            "SELFIE CAMERA": " 50 MP, f/2.0, (wide), AF ",
            "Loudspeaker": " Yes ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (under display, optical), accelerometer, gyro, proximity, compass ",
            "BATTERY": " Li-Po 4050 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 16,
        title: "Tecno Spark 8c",
        desc: "Android 11 (Go edition), HiOS 7.6",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_8Fl64VOCtD919BAyR2NmmjHAmv68hgRvkPm6mK4f.jpg",
        // Price and Price Quantity must be same
        price: 6999,
        priceQuantity: 6999,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "Dual Sim",
        specs: {
            RAM: "3 GB",
            ROM: "64 GB",
            "Network Technology": " GSM / HSPA / LTE ",
            "Announced": " 2022, January 31 ",
            "Status": " Available. Released 2022, February- ",
            "Dimensions": " 164.6 x 76 x 9 mm ",
            "Weight": " 180 g ",
            "Card slot": " Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 64 GB ",
            "MAIN CAMERA": " 13 MP, f/1.8, 27mm (wide) ",
            "SELFIE CAMERA": " 8 MP ",
            "Loudspeaker": " Yes ",
            "WLAN": " Yes ",
            "Sensors": " Fingerprint (rear-mounted), accelerometer, proximity ",
            "BATTERY": " Li-Po 5000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 17,
        title: "Samsung Galaxy S21",
        desc: "Android 11, One UI 3.1 Exynos 2100 (5 nm) - International CPU Octa-core (1x2.9 GHz Cortex-X1 & 3x2.80 GHz Cortex-A78 & 4x2.2 GHz Cortex-A55) GPU Mali-G78 MP14",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_ldTXSfaSyPN7bmTyB7WcixUsOeHyvEZG4LgikrmE.png",
        // Price and Price Quantity must be same
        price: 32999,
        priceQuantity: 32999,
        quantity: 1,
        category: "phones",
        popular: "yes",
        "Main Features": "5G",
        specs: {
            RAM: "8 GB",
            ROM: "256 GB",
            "Network Technology": " GSM / CDMA / HSPA / EVDO / LTE / 5G ",
            "Announced": " 2021, January 14 ",
            "Status": " Available. Released 2021, January 29 ",
            "Dimensions": " 151.7 x 71.2 x 7.9 mm ",
            "Weight": " 169 g ",
            "Card slot": " Dual SIM (2 Nano-SIMs + eSIM, dual stand-by) ",
            "Internal": " 256 GB ",
            "MAIN CAMERA": " 64 MP, f/2.0, 29mm (telephoto), 1/1.72, 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom ",
            "SELFIE CAMERA": " 10 MP, f/2.2, 26mm (wide), 1/3.24, 1.22µm, Dual Pixel PDAF ",
            "Loudspeaker": " Yes, with stereo speakers ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (under display, ultrasonic), accelerometer, gyro, proximity, compass, barometer ",
            "BATTERY": " Li-Ion 4000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 18,
        title: "Google Pixel 6",
        desc: "Android 12 Google Tensor (5 nm) CPU Octa-core (2x2.80 GHz Cortex-X1 & 2x2.25 GHz Cortex-A76 & 4x1.80 GHz Cortex-A55) GPU Mali-G78 MP20",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_5f6H1X53Q7E9J3bg7F5LogM7u5Up187MURKSwUhH.png",
        // Price and Price Quantity must be same
        price: 38999,
        priceQuantity: 38999,
        quantity: 1,
        category: "phones",
        popular: "yes",
        "Main Features": "5G",
        specs: {
            RAM: "8 GB",
            ROM: "256 GB",
            "Network Technology": " GSM / CDMA / HSPA / EVDO / LTE / 5G ",
            "Announced": " 2021, October 19 ",
            "Status": " Available. Released 2021, October 28 ",
            "Dimensions": " 158.6 x 74.8 x 8.9 mm ",
            "Weight": " 207 g",
            "Card slot": " Nano-SIM and/or eSIM ",
            "Internal": " 256 GB ",
            "MAIN CAMERA": " 50 MP, f/1.9, 25mm (wide), 1/1.31, 1.2µm, Dual Pixel PDAF, Laser AF, OIS ",
            "SELFIE CAMERA": " 8 MP, f/2.0, 24mm (wide), 1.12µm ",
            "Loudspeaker": " Yes, with stereo speakers ",
            "WLAN": " Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct, hotspot ",
            "Sensors": " Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer ",
            "BATTERY": " Li-Ion 4614 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 19,
        title: "Realme C25Y",
        desc: "Android 11, Realme UI R Unisoc T610 (12 nm) CPU Octa-core (2x1.8 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55) GPU Mali-G52 MP2",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_H1kfOS23C3m84ElMr8hqjHS3C7dYYmswqYvRRGui.png",
        // Price and Price Quantity must be same
        price: 7499,
        priceQuantity: 7499,
        quantity: 1,
        category: "phones",
        popular: "no",
        "Main Features": "feature",
        specs: {
            RAM: "4 GB",
            ROM: "64 GB",
            "Network Technology": " GSM / HSPA / LTE ",
            "Announced": " 2021, September 16 ",
            "Status": " Available. Released 2021, September 30 ",
            "Dimensions": " 164.5 x 76 x 9.1 mm ",
            "Weight": " 200 g ",
            "Card slot": " Dual SIM (Nano-SIM, dual stand-by) ",
            "Internal": " 64 GB ",
            "MAIN CAMERA": " 50 MP, f/1.8, 26mm (wide), PDAF ",
            "SELFIE CAMERA": " 8 MP, f/2.0, 26mm (wide), 1/4.0, 1.12µm",
            "Loudspeaker": " Yes ",
            "WLAN": " Wi-Fi 802.11 b/g/n, hotspot ",
            "Sensors": " Fingerprint (rear-mounted), accelerometer, proximity, compass ",
            "BATTERY": " Li-Po 5000 mAh, non-removable ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FFX",
        },
    },
    {
        id: 20,
        title: "SONY WH-1000XM5",
        desc: "The WH-1000XM5 earphones are not only equipped with two sets of processors that can control eight microphones, an automatic noise reduction optimizer that can automatically optimize the noise reduction function according to the wearing condition and environment, and a tailor-made driver unit, but also equipped with Industry-leading Noise Cancellation1 technology takes distraction-free listening and call clarity to a whole new level.",
        img: "https://www.sony.com/image/5d02da5df552836db894cead8a68f5f3?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
        // Price and Price Quantity must be same
        price: 20999,
        priceQuantity: 20999,
        quantity: 1,
        category: "headphones",
        popular: "yes",
        "Main Features": "Noise Cancelling",
        specs: {
            // RAM: "Bluetooth",
            // ROM: "5.0",
            "Bluetooth version": "5.2",
            "Active noise cancellation": "Yes",
            "Ambient mode": "Yes",
            "Multipoint": "Yes",
            "Battery life": "30 hours (ANC on), 40 hours (ANC off)",
            "Bluetooth codecs": "LDAC, AAC, SBC",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 21,
        title: "R-7000 Ronin",
        desc: "Ronin R-7000 Big Boss Wireless Headphone",
        img: "https://g9k7v3c5.stackpathcdn.com/pub/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/H/E/HEADPHONES-r-7000-ronin_spo.jpg",
        // Price and Price Quantity must be same
        price: 1900,
        priceQuantity: 1900,
        quantity: 1,
        category: "headphones",
        popular: "no",
        "Main Features": "5 hours battery",
        specs: {
            // RAM: "Bluetooth",
            // ROM: "5.0",
            "Bluetooth version": " 5 ",
            "Active noise cancellation": " No ",
            "Ambient mode": " Yes ",
            "Multipoint": " No ",
            "Battery life": " 320 mAh Talking/Music time about 5 hours ",
            "Bluetooth codecs": " LDAC, AAC ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 22,
        title: "R-9000 Ronin",
        desc: "Soft ear cushions and a 3.5 mm audio cable allow you to play music whether you're in the office, on a flight or on the go. ",
        img: "https://g9k7v3c5.stackpathcdn.com/pub/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/H/E/HEADPHONES-r-9000-ronin_spo.jpg",
        // Price and Price Quantity must be same
        price: 2199,
        priceQuantity: 2199,
        quantity: 1,
        category: "headphones",
        popular: "no",
        "Main Features": "4 hours battery",
        specs: {
            // RAM: "Bluetooth",
            // ROM: "5.0",
            "Bluetooth version": " 5 ",
            "Active noise cancellation": " No ",
            "Ambient mode": " Yes ",
            "Multipoint": " Yes ",
            "Battery life": " 4 hours ",
            "Bluetooth codecs": " LDAC, AAC, SBC ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 23,
        title: "Havit H610BT",
        desc: "With adjustable slider and soft padded headband allow you to get the most comfortable enjoyment.",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_4piqJNPybvP80JsryvDqGOawk4XyPVn1ufb4c2IW.jpg",
        // Price and Price Quantity must be same
        price: 2699,
        priceQuantity: 2699,
        quantity: 1,
        category: "headphones",
        popular: "no",
        "Main Features": "Fast charging | 12 Hours",
        specs: {
            // RAM: "Bluetooth",
            // ROM: "5.0",
            "Bluetooth version": " 5 ",
            "Active noise cancellation": " Yes ",
            "Ambient mode": " Yes ",
            "Multipoint": " No ",
            "Battery life": " 200mAh up to 12 hours",
            "Bluetooth codecs": " LDAC, AAC, SBC ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },
    {
        id: 24,
        title: "Audionic A-110",
        desc: "Presenting the best Wireless Bluetooth headphone Airbeats A-110. It is a perfect headset partner of your everyday music and calling needs.",
        img: "https://d1iv6qgcmtzm6l.cloudfront.net/products/lg_w7IFRo01jvLPNAi3sdhaHDIsquq2wa0G3l9FxDk9.jpg",
        // Price and Price Quantity must be same
        price: 2949,
        priceQuantity: 2949,
        quantity: 1,
        category: "headphones",
        popular: "no",
        "Main Features": "8 hours battery",
        specs: {
            // RAM: "Bluetooth",
            // ROM: "5.0",
            "Bluetooth version": " 5.2 ",
            "Active noise cancellation": " Yes ",
            "Ambient mode": " Yes ",
            "Multipoint": " Yes ",
            "Battery life": " up to 8 hours ",
            "Bluetooth codecs": " LDAC, AAC, SBC ",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },
    },


    {
        id: 25,
        title: "Nintendo Switch V2",
        desc: "The Nintendo Switch is both a home console and a handheld device - a hybrid of sorts. On the go, it'll be in the form of a tablet that also has a docking station which then plugs into your TV.",
        img: "https://s.pacn.ws/1500/xe/nintendo-switch-neon-blue-neon-red-601273.6.jpg",
        // Price and Price Quantity must be same
        price: 14500,
        priceQuantity: 14500,
        quantity: 1,
        category: "consoles",
        popular: "yes",
        "Main Features": "4-9 hours battery",
        specs: {
            RAM: "TV mode",
            ROM: "Handheld mode",
            "Version": "Japan",
            "Colors": "Neon Blue, Neon Red",
            "Official release date": "Aug 30, 2019",
            "Product measurement": "35cm x 20cm x 10cm",
           
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },

        
    },
    {
        id: 26,
        title: "Nintendo Animal Crossing",
        desc: "added on our class og aug 8 , 2022",
        img: "https://s1.thcdn.com/productimg/960/960/12458084-6214741408005972.jpg",
        // Price and Price Quantity must be same
        price: 16000,
        priceQuantity: 16000,
        quantity: 1,
        category: "consoles",
        popular: "no",
        "Main Features": "4-9 hours battery, TV mode, handheld mode",
        specs: {
            RAM: "",
            ROM: "",
            "Version": "Japan",
            "Colors": "Neon Blue, Neon Red",
            "Official release date": "Aug 30, 2019",
            "Product measurement": "35cm x 20cm x 10cm",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },

        
    },
    {
        id: 27,
        title: "Nintendo Switch Lite",
        desc: "Nintendo Switch Lite is a compact, lightweight Nintendo Switch system dedicated to handheld play. With a built-in +Control Pad and a sleek, unibody design, it’s great for on-the-go gaming. Nintendo Switch Lite is compatible with the robust library of Nintendo Switch games that support handheld mode. If you’re looking for a gaming system all your own, Nintendo Switch Lite is ready to hit the road whenever you are.",
        img: "https://s.pacn.ws/1500/xc/nintendo-switch-lite-turquoise-600347.4.jpg?v=qm8wxn&width=800",
        // Price and Price Quantity must be same
        price: 7500,
        priceQuantity: 7500,
        quantity: 1,
        category: "consoles",
        popular: "no",
        "Main Features": "Handheld play, Light, Compact",
        specs: {
            RAM: "",
            ROM: "",
            "Version": "Japan",
            "Colors": "Turquoise",
            "Official release date": "Aug 30, 2019",
            "Product measurement": "35cm x 20cm x 10cm",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },

        
    },
    {
        id: 28,
        title: "XBOX Series X",
        desc: "Xbox Series X will be the fastest, most powerful console ever and set a new bar for performance, speed and compatibility, allowing to bring the gaming legacy, thousands of games from three generations and more forward with you. Its industrial design enables us to deliver four times the processing power of Xbox One X in the quietest and efficient way, something that is critically important in delivering truly immersive gameplay. The design supports both vertical and horizontal orientation.",
        img: "https://s.pacn.ws/1500/y8/xbox-series-x-616469.4.webp?v=qm62qq&width=760",
        // Price and Price Quantity must be same
        price: 40655,
        priceQuantity: 40655,
        quantity: 1,
        category: "consoles",
        popular: "yes",
        "Main Features": "Hardware Accelerated DirectX Raytracing",
        specs: {
            RAM: "",
            ROM: "",
            "Version": "Japan",
            "Colors": "Black",
            "Official release date": "Nov 10, 2020",
            "Product measurement": "38cm x 30cm x 22cm",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },

        
    },
    {
        id: 29,
        title: "Playstation 5",
        desc: "Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.",
        img: "https://s.pacn.ws/1500/z4/-632313.1.webp?v=qm8444&width=760",
        // Price and Price Quantity must be same
        price: 52270,
        priceQuantity: 40655,
        quantity: 1,
        category: "consoles",
        popular: "yes",
        "Main Features": "Haptic technology",
        specs: {
            RAM: "",
            ROM: "",
            "Version": "Asia",
            "Colors": "White",
            "Official release date": "Nov 19, 2020",
            "Product measurement": "47cm x 42cm x 18cm",
        },
        colors: {
            color1: "58FF33",
            color2: "FF33F3",
            color3: "3346FF",
        },

        
    },
];

// Items added to cart 
export const CartItemsData = [
    // Cart Items will be added here through product buttons - update via states
];
export const totaPriceOfCartItemsData = []; // this will recive data form the totalPrice function in Cart.jsx and then will be retrived to App.js state;

// export const popularProducts = [
// ];